[pytest]
testpaths = tests
norecursedirs =
    .git
    .venv
    build
    dist
    .idea
    .pytest_cache
    .pytest_tmp
    .test_tmp
    pytest-cache-files-*
    tests/.pytest_tmp
    tests/pytest-cache-files-*
